# Generated by Django 5.2 on 2025-05-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='情緒類型名稱')),
            ],
            options={
                'verbose_name': '情緒類型',
                'verbose_name_plural': '情緒類型',
            },
        ),
        migrations.AlterField(
            model_name='emotion',
            name='emotion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emotions', to='emotion.emotion_type', verbose_name='情緒類型'),
        ),
    ]
