# Generated by Django 5.2 on 2025-05-14 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme_Random_Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='擲骰時間')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_rolls', to='planner.travel_themes', verbose_name='旅行主題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_rolls', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '主題隨機骰子',
                'verbose_name_plural': '主題隨機骰子',
                'ordering': ['-created_at'],
            },
        ),
    ]
