# Generated by Django 5.2 on 2025-05-14 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='主題名稱')),
                ('description', models.TextField(verbose_name='主題描述')),
                ('image_url', models.URLField(verbose_name='主題URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '旅行主題',
                'verbose_name_plural': '旅行主題',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_ids', models.TextField(verbose_name='景點ID列表')),
                ('activity_ids', models.TextField(verbose_name='活動ID列表')),
                ('start_date', models.DateField(verbose_name='行程開始日期')),
                ('end_date', models.DateField(verbose_name='行程結束日期')),
                ('min_budget', models.FloatField(verbose_name='最低預算')),
                ('max_budget', models.FloatField(verbose_name='最高預算')),
                ('total_cost', models.FloatField(verbose_name='旅遊預算')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='planner.travel_themes', verbose_name='行程主題')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='景點名稱')),
                ('description', models.TextField(verbose_name='景點描述')),
                ('address', models.TextField(verbose_name='地址')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='經度')),
                ('image_url', models.URLField(verbose_name='景點圖片URL')),
                ('category', models.TextField(verbose_name='類別')),
                ('opening_hours', models.TextField(verbose_name='營業時間')),
                ('min_price', models.FloatField(verbose_name='最低費用')),
                ('max_price', models.FloatField(verbose_name='最高費用')),
                ('duration', models.IntegerField(verbose_name='預計遊覽時間（分鐘）')),
                ('contact_info', models.TextField(verbose_name='景點聯絡資訊')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='planner.travel_themes', verbose_name='旅行主題')),
            ],
            options={
                'verbose_name': '景點',
                'verbose_name_plural': '景點',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='活動名稱')),
                ('description', models.TextField(verbose_name='活動描述')),
                ('location', models.CharField(max_length=200, verbose_name='活動地點')),
                ('image_url', models.URLField(verbose_name='圖片網址')),
                ('recommended_for', models.TextField(verbose_name='適合的旅行主題')),
                ('min_price', models.FloatField(verbose_name='最低費用')),
                ('max_price', models.FloatField(verbose_name='最高費用')),
                ('duration', models.IntegerField(verbose_name='活動時間(分鐘)')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.destination', verbose_name='關聯景點')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.travel_themes', verbose_name='旅行主題')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動',
            },
        ),
    ]
