# Generated by Django 5.2 on 2025-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_emotion_type_alter_emotion_emotion_type'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='travel_themes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='travel_themes',
            name='image_url',
        ),
        migrations.AddField(
            model_name='destination',
            name='suitable_emotions',
            field=models.ManyToManyField(blank=True, related_name='suitable_destinations', to='emotion.emotion_type', verbose_name='適合情緒類型'),
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
