# Generated by Django 4.2.5 on 2025-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_destination_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='max_price',
            field=models.FloatField(blank=True, null=True, verbose_name='最高費用'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='min_price',
            field=models.FloatField(blank=True, null=True, verbose_name='最低費用'),
        ),
    ]
